### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by dikaio** [alisterscott/webdriver-user-agent#19]
Hi guys. I've run into this error while running with the example in the README. the line that produced the error was:

``` ruby
driver = Webdriver::UserAgent.driver(:browser => :chrome, :agent => :iphone, :orientation => :landscape)
```

``` ruby
NoMethodError: undefined method `load_file' for Psych:Module
```

Hoping someones run into this before :/

**Comment by samnissen** [comment]
@dikaio I don't consider this 'closed', so I added Psych to the gemspec in PR #23
