### ISSUE TITLE
Extend the gem to allow setting of the browser 'version' that is reported

### ISSUE THREAD

**Issue by Chuckv** [alisterscott/webdriver-user-agent#2]
would make it very useful for testing of responses where a site needs to do something like issue a warning if the browser version is too ancient for the site to properly support it.   simulating older versions of firefox or IE come to mind as potential uses here.

If I'm reading thing correctly, with chrome and the user-agent switch, we could have it say nearly anything we wanted, it could claim to be a windows phone, or (shudder) IE5.5 or heck even some ancient version of netscrape.

**Comment by samnissen** [comment]
@Chuckv @cheezy As the pull request is merged, can this issue be closed?

**Comment by Chuckv** [comment]
Mea culpa, did not see the changed.  Ill try to check on it in the next day
or two, if you hear nothing negative from me by Monday please close the
issue

**Comment by Chuckv** [comment]
So looking at this, my only initial question would be around the unit test

+  it "can create a new webdriver driver using firefox and user-specified user agent" do
+   @driver = Webdriver::UserAgent.driver(:user_agent_string => "Mozilla/4.0 (compatible; MSIE 5.5b1; Mac_PowerPC)")
+   expect(@driver.browser).to eq(:firefox)
+   expect(@driver.execute_script('return navigator.userAgent')).not_to be_nil

not_to be_nil seems a bit of a strange validation to me  I would have maybe expected something more like

expect(@driver.execute_script('return navigator.userAgent')).to include 'Mac_PowerPC'

Time to play with this a little via irb and see what is actually there in the request header

**Comment by samnissen** [comment]
I agree -- that is a better test. Let me know how you get on or if you want me to dive in to re-write the test.

**Comment by samnissen** [comment]
@Chuckv This can be closed.

**Comment by samnissen** [comment]
@Chuckv @cheezy As the improved tests were merged, can this issue be closed?
