### ISSUE TITLE
Compatibility with Selenium 3

### ISSUE THREAD

**Issue by billedwards1890** [alisterscott/webdriver-user-agent#33]
Hi there, when I attempt to use this package with Selenium 3, I get the following error:

ArgumentError: unknown option: {:profile=>#<Selenium::WebDriver::Firefox::Profile:0x0000000306c9f0 @model=nil, @native_events=false, @secure_ssl=false, @untrusted_issuer=true, @load_no_focus_lib=false, @additional_prefs={"general.useragent.override"=>"Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B435 Safari/600.1.4"}, @extensions={}>}

Is there any plans to support selenium 3, or am I missing something? Thank you!

**Comment by cheezy** [comment]
I’ll take a look at this over the weekend.

**Comment by billedwards1890** [comment]
Hi there, just wanted to update and say that updating from selenium-webdriver 3.0.1 to 3.0.5 fixed this issue for me per this thread: https://github.com/SeleniumHQ/selenium/issues/2933
