### ISSUE TITLE
Freeze when trying to use with Watir 6.10

### ISSUE THREAD

**Issue by futurecraft** [alisterscott/webdriver-user-agent#36]
Hi!

First of all - thanks for the gem, it looks super handy.
But unfortunately it doesn't work for me.

So I'm using Ruby 2.3.3 with watir 6.10.3 (tried Mac OS and Windows units)
```
require 'watir'
require 'webdriver-user-agent'
driver = Webdriver::UserAgent.driver(browser: :chrome, agent: :iphone, orientation: :landscape)
```
at this point Chrome launches, resizing right away to a correct window size
`browser = Watir::Browser.new driver`
after this line command execution freezes for more then a minute, but still returns what is likely to be a correct result:
`#<Watir::Browser:0x3ff8567f7388>`
but trying to access some page with `browser.goto` results in freeze and then with the following output:
```
Net::ReadTimeout: Net::ReadTimeout
from blablabla/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
```
Can you please give me a hint on what can I try?

Please let me know if I should provide more details

**Comment by samnissen** [comment]
I can replicate this with ruby 2.4.

Can you try asking the Watir Slack channel? http://watir.com/help/

**Comment by samnissen** [comment]
@futurecraft Did you ever get any clarity here?

I tried again today and can no longer replicate:

```ruby
$ gem list watir

*** LOCAL GEMS ***

watir (6.12.0)
$ gem list webdriver-user-agent

*** LOCAL GEMS ***

webdriver-user-agent (7.5)
$ irb
2.4.1 :001 > require 'webdriver-user-agent'
 => true
2.4.1 :002 > require 'watir'
 => true
2.4.1 :003 > driver = Webdriver::UserAgent.driver(browser: :chrome, agent: :iphone, orientation: :landscape)
 => #<Selenium::WebDriver::Chrome::Driver:0x..f85f943529f03e24c browser=:chrome>
2.4.1 :004 > browser = Watir::Browser.new driver
 => #<Watir::Browser:0x3fbe7bd4e4e47c6 url="data:," title="">
2.4.1 :005 > browser.goto "https://daringfireball.net"
 => "https://daringfireball.net"
2.4.1 :006 > browser.goto "https://maximumfun.org"
 => "https://maximumfun.org"
2.4.1 :007 > browser.close
 => true
```

**Comment by samnissen** [comment]
@sandeepnagra I'm recommending this be closed -- let me know what you think.

**Comment by sandeepnagra** [comment]
@samnissen - I agree. No update from reporter in long time and you can't replicate it so I am closing this issue.
