### ISSUE TITLE
Selenium :args or :switches is deprecated

### ISSUE THREAD

**Issue by samnissen** [alisterscott/webdriver-user-agent#37]
> driver = Webdriver::UserAgent.driver(browser: :chrome, agent: :iphone, orientation: :landscape)
    2018-05-09 06:03:45 WARN Selenium [DEPRECATION] :args or :switches is deprecated. Use Selenium::WebDriver::Chrome::Options#add_argument instead.

**Comment by sandeepnagra** [comment]
I get following error on Firefox:
`/Users/xxxxx/.rvm/rubies/ruby-2.4.1/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/mm57710/RubymineProjects/test/device_agent.rb
2018-08-06 16:42:15 WARN Selenium [DEPRECATION] :profile is deprecated. Use Selenium::WebDriver::Firefox::Options#profile= instead.
WebDriverError@chrome://marionette/content/error.js:172:5: Selenium::WebDriver::Error::WebDriverError
	from InsecureCertificateError@chrome://marionette/content/error.js:291:5
	from handleReadyState@chrome://marionette/content/listener.js:266:21
	from handleEvent@chrome://marionette/content/listener.js:239:9
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:69:in 'assert_ok'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:32:in 'initialize'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in 'new'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in 'create_response'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:104:in 'request'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in 'call'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in 'execute'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in 'execute'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:57:in 'get'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/navigation.rb:30:in 'to'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/watir-6.8.1/lib/watir/browser.rb:82:in 'goto'
	from /Users/mm57710/RubymineProjects/test/device_agent.rb:7:in '<top (required)>'
	from -e:1:in 'load'
	from -e:1:in '<main>'

Process finished with exit code 1
`

**Comment by samnissen** [comment]
@sandeepnagra Are you on the Watir Slack? I suggest we open this up on there. 

FWIW I'm happy to help you manage this, and have a branch on PR #34 which I think should be the first step.

**Comment by samnissen** [comment]
@sandeepnagra You should be able to directly use my repo, which also merges #34, until this is merged: https://github.com/samnissen/webdriver-user-agent

**Comment by sandeepnagra** [comment]
Perfect! Thanks @samnissen. I will work on that repo directly.
