### ISSUE TITLE
Add how to pass Chrome options on documentation

### ISSUE THREAD

**Issue by allanjba** [alisterscott/webdriver-user-agent#43]
I don't understand how I am supposed to pass the chrome options for this set up.
On Watir I can do `Watir::Browser.new :chrome, opts` 
But id doesn't work if I try `Watir::Browser.new(driver) opts`

**Comment by samnissen** [comment]
@allanjba I can't speak to how Watir works, but in this case, the syntax would more likely be `Watir::Browser.new(driver, opts)`.

If you'd like to add some functionality to webdriver-user-agent to pass user-provided options to the profile or the webdriver, I'd certainly welcome a pull request to do that.

**Comment by allanjba** [comment]
Sorry I am not very experienced. Maybe it is a simple question but. I am trying to set the _--user-data-dir_ for chrome. 
I can do this with watir
 `browser = Watir::Browser.new :chrome, options: {args: ['--user-data-dir=/cookies']}`
But when I try with webdriver-user-agent it doesn't work:
```
driver = Webdriver::UserAgent.driver(browser: :chrome, agent: :iphone)
browser = Watir::Browser.new driver,  options: {args: ['--user-data-dir=/cookies']}`
```
I tried a lot of different ways but none of the ones I tried worked
Could you help me with a direction here?

**Comment by samnissen** [comment]
Hi @allanjba I think you're on the right track, only need to pass the parameter you need to the function call I'd suggest an array of parameters, then iterate over them to add them to the Chrome or Firefox, like `opts.each{|x| options[:options].add_argument x}`. I think in Safari we'd want to raise an error unless there's a way to modify the profile?

I hope you'll submit this PR!
